{% set name = "eudist" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/eudist-{{ version }}.tar.gz
  sha256: ac6976ca21a7c3fab1053b3c02304a431071efe89160b954a97e04e62f32ac17
  patches:
    - "windows.patch" # the patch file is expected to be found in the recipe

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - cython
    - setuptools-scm
    - setuptools >=42
    - setuptools-scm >=3.4
    - setuptools_scm_git_archive
    - pip
  run:
    - python

test:
  imports:
    - eudist
  requires:
    - pip
    - pytest
  source_files:
    - eudist
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/dschwoerer/eudist
  summary: Calculate distances between simple shapes such as polygons.
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - dschwoerer
    - johnomotani
