{% set name = "eudist" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eudist-{{ version }}.tar.gz
  sha256: 1f0805eb0af592907584b10ebefb6c1636d34d7ff0e08726515176e55200000c

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - cython
    - setuptools-scm
    - setuptools >=42
    - setuptools-scm >=3.4
    - setuptools_scm_git_archive
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - eudist
  requires:
    - pip
    - pytest
  source_files:
    - eudist
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/dschwoerer/eudist
  summary: Calculate distances between simple shapes such as polygons.
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - dschwoerer
    - johnomotani
