{% set name = "eudist" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eudist-{{ version }}.tar.gz
  sha256: 007e9d147de3d61578f263eabe3766bc8eff07e211a6b0d62aa8179cddb8d02b

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - cython
    - setuptools-scm
    - setuptools >=42
    - setuptools-scm >=3.4
    - setuptools_scm_git_archive
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - eudist
  requires:
    - pip
    - pytest
  source_files:
    - eudist
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/dschwoerer/eudist
  summary: Calculate distances between simple shapes such as polygons.
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - dschwoerer
    - johnomotani
